from pathlib import Path
import re

path = Path("README.md")
text = path.read_text(encoding="utf-8")

# The research library is private/internal. Do not advertise or link it publicly.
text = re.sub(
    r'\n?<a href="https://github\.com/Lapinite\?tab=stars"><img[^\n]*Research-Library[^\n]*</a>\n?',
    "\n",
    text,
)

# Remove redundant implementation captions. The visuals should speak for themselves.
text = text.replace(
    '\n<p align="center"><sub>The Pacman graph is generated by GitHub Actions and stored in this profile repository.</sub></p>\n',
    "\n",
)
text = text.replace(
    '\n<p align="center"><sub>Generated from public GitHub repositories and public activity only. Private repositories and proprietary source code are excluded.</sub></p>\n',
    "\n",
)

# Remove the public Research & Engineering Library section and its star-list link.
text = re.sub(
    r'\n## Research & Engineering Library\n.*?(?=\n## Developer Resources\n)',
    "\n",
    text,
    flags=re.S,
)

# Collapse excessive blank lines introduced by removals.
text = re.sub(r'\n{4,}', '\n\n\n', text)

path.write_text(text, encoding="utf-8", newline="\n")
