from pathlib import Path
import re

path = Path("README.md")
text = path.read_text(encoding="utf-8")

# The v5 profile README is intentionally visual-first. Keep scheduled refreshes
# from recreating legacy sections while still normalizing generated copy.
replacements = {
    "Current Leviathan Development Stack": "Development Stack",
    "Experience & Commerce Flows": "Experience & Commerce",
    "Public Developer Repositories": "Public Developer Network",
    "Leviathan Development Activity": "Live Development Telemetry",
    "Live Public Activity": "Recent Public Activity",
    "Public Repository Health": "Repository Health",
    "Public Development Analytics": "Development Analytics",
}
for old, new in replacements.items():
    text = text.replace(old, new)

for forbidden in [
    "Browse public research lists",
    "The Pacman graph is generated by GitHub Actions and stored in this profile repository.",
    "Generated from public GitHub repositories and public activity only. Private repositories and proprietary source code are excluded.",
]:
    text = text.replace(forbidden, "")

text = re.sub(r"\n{4,}", "\n\n\n", text)
path.write_text(text, encoding="utf-8", newline="\n")
